import { useEffect, useState } from 'react';
import { api } from '../../api/client';
import Status from '../../components/Status';
import { EmptyState, ErrorMessage } from '../../components/LoadingError';

export function Menu() {
  const [items, setItems] = useState([]); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { api.get('/menu', { params: { search } }).then((r) => setItems(r.data)).catch((err) => setError(err.message)); }, [search]);
  async function add(item) { try { await api.post('/cart/items', { menu_item_id: item.id, quantity: 1 }); setMessage(`${item.item_name} added to cart.`); } catch (err) { setError(err.message); } }
  return <section><div className="mb-5 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h1 className="text-3xl font-black">Food Menu</h1><p className="text-slate-600">Browse vendors and add available food to your cart.</p></div><input className="input md:max-w-sm" placeholder="Search food or vendor" value={search} onChange={(e) => setSearch(e.target.value)} /></div><ErrorMessage error={error} />{message && <div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-emerald-700">{message}</div>}{items.length === 0 ? <EmptyState>No menu items found.</EmptyState> : <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map((item) => <article className="card" key={item.id}><img src={item.image || 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c'} alt={item.item_name} className="h-40 w-full rounded-xl object-cover" /><div className="mt-4 flex items-start justify-between gap-3"><div><h2 className="text-xl font-black">{item.item_name}</h2><p className="text-sm text-slate-500">{item.vendor_name}</p></div><p className="font-black text-emerald-700">${Number(item.price).toFixed(2)}</p></div><p className="mt-2 min-h-12 text-sm text-slate-600">{item.description}</p><div className="mt-4 flex items-center justify-between"><span className="text-sm font-semibold">Stock: {item.stock_quantity}</span><button className="btn" disabled={!item.available || item.stock_quantity < 1} onClick={() => add(item)}>Add to cart</button></div></article>)}</div>}</section>;
}

export function Cart() {
  const [cart, setCart] = useState({ items: [], total: 0 }); const [pickup, setPickup] = useState(() => new Date(Date.now() + 3600000).toISOString().slice(0, 16)); const [paymentMethod, setPaymentMethod] = useState('Campus Card'); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  async function load() { try { const { data } = await api.get('/cart'); setCart(data); } catch (err) { setError(err.message); } }
  useEffect(() => { load(); }, []);
  async function update(id, quantity) { try { await api.put(`/cart/items/${id}`, { quantity: Number(quantity) }); load(); } catch (err) { setError(err.message); } }
  async function remove(id) { try { await api.delete(`/cart/items/${id}`); load(); } catch (err) { setError(err.message); } }
  async function checkout() { try { const { data } = await api.post('/orders/checkout', { pickup_time: new Date(pickup).toISOString(), payment_method: paymentMethod }); setMessage(`Order #${data.id} placed. Queue #${data.queue_number}.`); load(); } catch (err) { setError(err.message); } }
  return <section className="grid gap-6 lg:grid-cols-3"><div className="card lg:col-span-2"><h1 className="text-3xl font-black">Cart</h1><ErrorMessage error={error} />{message && <div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-emerald-700">{message}</div>}{cart.items.length === 0 ? <EmptyState>Your cart is empty.</EmptyState> : cart.items.map((item) => <div className="flex flex-col gap-3 border-b py-4 md:flex-row md:items-center md:justify-between" key={item.id}><div><p className="font-bold">{item.item_name}</p><p className="text-sm text-slate-500">{item.vendor_name} · ${Number(item.price).toFixed(2)}</p></div><div className="flex items-center gap-3"><input className="input w-24" type="number" min="1" value={item.quantity} onChange={(e) => update(item.id, e.target.value)} /><button className="rounded-xl border px-3 py-2" onClick={() => remove(item.id)}>Remove</button><strong>${Number(item.subtotal).toFixed(2)}</strong></div></div>)}</div><aside className="card h-fit"><h2 className="text-2xl font-black">Checkout</h2><label className="label mt-4 block">Pickup time<input className="input mt-1" type="datetime-local" value={pickup} onChange={(e) => setPickup(e.target.value)} /></label><label className="label mt-4 block">Payment method<select className="input mt-1" value={paymentMethod} onChange={(e) => setPaymentMethod(e.target.value)}><option>Campus Card</option><option>Credit Card</option><option>Mobile Wallet</option><option>Cash at Pickup</option></select></label><div className="mt-4 flex justify-between text-xl font-black"><span>Total</span><span>${Number(cart.total).toFixed(2)}</span></div><button className="btn mt-5 w-full" disabled={!cart.items.length} onClick={checkout}>Checkout & pay</button></aside></section>;
}

export function Orders({ title = 'Orders' }) {
  const [orders, setOrders] = useState([]); const [error, setError] = useState('');
  useEffect(() => { const load = () => api.get('/orders').then((r) => setOrders(r.data)).catch((err) => setError(err.message)); load(); const timer = setInterval(load, 10000); return () => clearInterval(timer); }, []);
  return <section><h1 className="mb-4 text-3xl font-black">{title}</h1><ErrorMessage error={error} />{orders.length === 0 ? <EmptyState>No orders yet.</EmptyState> : <div className="grid gap-3">{orders.map((order) => <article className="card flex flex-col gap-3 md:flex-row md:items-center md:justify-between" key={order.id}><div><p className="font-black">Order #{order.id} · Queue #{order.queue_number}</p><p className="text-slate-600">{order.vendor_name} · pickup {new Date(order.pickup_time).toLocaleString()}</p></div><div className="flex items-center gap-3"><Status value={order.status} /><Status value={order.payment_status} /><strong>${Number(order.total_amount).toFixed(2)}</strong></div></article>)}</div>}</section>;
}

export function Reviews() {
  const [vendors, setVendors] = useState([]); const [reviews, setReviews] = useState([]); const [form, setForm] = useState({ vendor_id: '', rating: 5, comment: '' }); const [error, setError] = useState('');
  async function load() { const [v, r] = await Promise.all([api.get('/vendors'), api.get('/reviews')]); setVendors(v.data); setReviews(r.data); }
  useEffect(() => { load().catch((err) => setError(err.message)); }, []);
  async function submit(e) { e.preventDefault(); try { await api.post('/reviews', { ...form, vendor_id: Number(form.vendor_id), rating: Number(form.rating) }); setForm({ vendor_id: '', rating: 5, comment: '' }); load(); } catch (err) { setError(err.message); } }
  return <section className="grid gap-6 lg:grid-cols-3"><form onSubmit={submit} className="card h-fit"><h1 className="text-2xl font-black">Submit review</h1><ErrorMessage error={error} /><select className="input mt-4" required value={form.vendor_id} onChange={(e) => setForm({ ...form, vendor_id: e.target.value })}><option value="">Choose vendor</option>{vendors.map((v) => <option key={v.id} value={v.id}>{v.vendor_name}</option>)}</select><input className="input mt-3" type="number" min="1" max="5" value={form.rating} onChange={(e) => setForm({ ...form, rating: e.target.value })} /><textarea className="input mt-3" rows="4" value={form.comment} onChange={(e) => setForm({ ...form, comment: e.target.value })} /><button className="btn mt-4 w-full">Submit rating</button></form><div className="lg:col-span-2 grid gap-3">{reviews.map((review) => <article className="card" key={review.id}><p className="font-black">{review.vendor_name} · {'★'.repeat(review.rating)}</p><p className="text-slate-600">{review.comment}</p><p className="mt-2 text-sm text-slate-400">by {review.student_name}</p></article>)}</div></section>;
}
